[package]
name = "tempc"
version = "0.1.0"
authors = ["Blizire <stiles.trenton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
